<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-06-27 12:36

$extensionPath = t3lib_extMgm::extPath('ip_issuu');
$extensionClassesPath = t3lib_extMgm::extPath('ip_issuu') . 'Classes/';
return array(
	'tx_ipissuu_controller_indexcontroller' => $extensionClassesPath . 'Controller/Index.php',
	'tx_ipissuu_domain_model_flip' => $extensionClassesPath . 'Domain/Model/Flip.php',
);
?>